import { useState, useEffect } from "react";
import Navbar from "../components/Navbar";

const ReportPage = () => {
  const [controls, setControls] = useState([]);
  const [streaming, setStreaming] = useState(false);
  const [streamText, setStreamText] = useState("");
  const [done, setDone] = useState(false);

  useEffect(() => {
    const stored = JSON.parse(localStorage.getItem("controls")) || [];
    setControls(stored);
  }, []);

  const handleGenerateReport = () => {
    if (controls.length === 0) { alert("Add some controls first!"); return; }
    setStreaming(true);
    setStreamText("");
    setDone(false);

    const total = controls.length;
    const active = controls.filter((c) => c.status === "ACTIVE").length;
    const overdue = controls.filter((c) => c.status === "OVERDUE").length;
    const critical = controls.filter((c) => c.riskLevel === "CRITICAL").length;
    const avgScore = Math.round(controls.reduce((sum, c) => sum + Number(c.score), 0) / total);

    const reportText = `
📊 CONTINUOUS CONTROL MONITORING REPORT
Generated: ${new Date().toLocaleDateString()}
${"─".repeat(50)}

📋 EXECUTIVE SUMMARY
This report provides an overview of ${total} monitored controls. Overall compliance score: ${avgScore}/100 — ${avgScore >= 80 ? "strong" : avgScore >= 50 ? "moderate" : "weak"} compliance posture.

📈 KEY METRICS
- Total Controls: ${total}
- Active Controls: ${active}
- Overdue Controls: ${overdue}
- Critical Risk Controls: ${critical}
- Average Compliance Score: ${avgScore}/100

⚠️ RISK ANALYSIS
${critical > 0 ? `ALERT: ${critical} control(s) at CRITICAL risk — escalate immediately.` : "No critical risks detected."}
${overdue > 0 ? `WARNING: ${overdue} control(s) are overdue and need urgent attention.` : "All controls within scheduled review dates."}

💡 TOP RECOMMENDATIONS
1. ${avgScore < 70 ? "Urgently improve compliance score — immediate remediation required." : "Maintain current compliance procedures."}
2. ${overdue > 0 ? `Schedule review meetings for all ${overdue} overdue controls.` : "Continue current monitoring schedule."}
3. ${critical > 0 ? `Escalate ${critical} critical risk control(s) to management.` : "Perform quarterly risk assessments."}
4. Implement automated alerts for controls scoring below 70.
5. Conduct monthly compliance reviews to track improvement.

✅ CONCLUSION
${avgScore >= 80 ? "Strong compliance demonstrated. Continue current practices." : avgScore >= 50 ? "Moderate compliance. Several areas require improvement." : "Immediate action required. Compliance levels are critically low."}

${"─".repeat(50)}
Report generated by Control Monitoring AI System
    `.trim();

    const words = reportText.split(" ");
    let index = 0;
    const interval = setInterval(() => {
      if (index < words.length) {
        setStreamText((prev) => prev + (index === 0 ? "" : " ") + words[index]);
        index++;
      } else {
        clearInterval(interval);
        setStreaming(false);
        setDone(true);
      }
    }, 30);
  };

  const handleDownloadReport = () => {
    const blob = new Blob([streamText], { type: "text/plain;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", "control_monitoring_report.txt");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="min-h-screen bg-gray-50">

      {/* ✅ Responsive Navbar */}
      <Navbar />

      <div className="max-w-4xl mx-auto p-4 md:p-6 space-y-6">

        <div className="bg-white rounded-2xl shadow p-6">
          <h2 className="text-2xl font-bold text-[#1B4F8A] mb-2">📊 AI Report Generator</h2>
          <p className="text-gray-500 text-sm">Generate a full compliance report. The report streams live as it is being generated.</p>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4">
            <div className="bg-blue-50 rounded-xl p-3 text-center">
              <p className="text-2xl font-bold text-[#1B4F8A]">{controls.length}</p>
              <p className="text-xs text-gray-500">Total Controls</p>
            </div>
            <div className="bg-green-50 rounded-xl p-3 text-center">
              <p className="text-2xl font-bold text-green-600">{controls.filter((c) => c.status === "ACTIVE").length}</p>
              <p className="text-xs text-gray-500">Active</p>
            </div>
            <div className="bg-red-50 rounded-xl p-3 text-center">
              <p className="text-2xl font-bold text-red-600">{controls.filter((c) => c.status === "OVERDUE").length}</p>
              <p className="text-xs text-gray-500">Overdue</p>
            </div>
            <div className="bg-purple-50 rounded-xl p-3 text-center">
              <p className="text-2xl font-bold text-purple-600">
                {controls.length > 0 ? Math.round(controls.reduce((s, c) => s + Number(c.score), 0) / controls.length) : 0}
              </p>
              <p className="text-xs text-gray-500">Avg Score</p>
            </div>
          </div>

          <button
            onClick={handleGenerateReport}
            disabled={streaming}
            className="mt-4 bg-[#1B4F8A] hover:bg-blue-800 disabled:bg-gray-400 text-white px-6 py-2.5 rounded-lg font-semibold transition flex items-center gap-2"
          >
            {streaming ? (
              <>
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                Generating Report...
              </>
            ) : "⚡ Generate AI Report"}
          </button>
        </div>

        {(streamText || streaming) && (
          <div className="bg-white rounded-2xl shadow p-6">
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-3 mb-4">
              <h3 className="text-lg font-bold text-[#1B4F8A]">📄 Generated Report</h3>
              <div className="flex items-center gap-3">
                {streaming && (
                  <span className="flex items-center gap-2 text-sm text-blue-600">
                    <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />
                    Streaming...
                  </span>
                )}
                {done && <span className="text-sm text-green-600 font-semibold">✅ Complete</span>}
                {done && (
                  <button
                    onClick={handleDownloadReport}
                    className="bg-green-500 hover:bg-green-600 text-white px-4 py-1.5 rounded-lg text-sm font-semibold transition"
                  >
                    ⬇️ Download
                  </button>
                )}
              </div>
            </div>
            <div className="bg-gray-50 border border-gray-200 rounded-xl p-4 font-mono text-sm text-gray-700 whitespace-pre-wrap min-h-64 max-h-96 overflow-y-auto">
              {streamText}
              {streaming && <span className="inline-block w-2 h-4 bg-blue-500 ml-1 animate-pulse" />}
            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default ReportPage;